# Generated by Django 3.2.5 on 2021-07-31 21:33

import datetime
from django.db import migrations, models
import django_mysql.models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity99', models.DecimalField(decimal_places=1, max_digits=4, validators=[movies.models.validate_popularity])),
                ('director', models.CharField(max_length=50)),
                ('genre', django_mysql.models.ListCharField(models.CharField(max_length=15), max_length=165, size=10)),
                ('imdb_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[movies.models.validate_imdb_score])),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 1, 3, 3, 4, 30085))),
            ],
            options={
                'unique_together': {('name', 'director')},
            },
        ),
    ]
