# Generated by Django 3.2.5 on 2021-07-26 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 22, 30, 20, 732890)),
        ),
        migrations.AlterField(
            model_name='movies',
            name='imdb_score',
            field=models.CharField(max_length=100),
        ),
    ]
