# Generated by Django 3.2.5 on 2021-07-28 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210726_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 17, 0, 45, 546420)),
        ),
    ]
